# Generated by Django 5.0.2 on 2024-03-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgnWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='threshold',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='router',
            name='ip_Address',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='router',
            name='mac_Address',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
