# Generated by Django 5.0.2 on 2024-03-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgnWebApp', '0002_alter_alarm_address_alter_alarm_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='address',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='on_Delay',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='threshold_Type',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='Country',
        ),
        migrations.AddField(
            model_name='machine',
            name='city',
            field=models.CharField(default='Vicenza', max_length=20),
        ),
        migrations.AddField(
            model_name='machine',
            name='linux_Version',
            field=models.CharField(default='v0', max_length=10),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='access_category',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='severity',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='kgnbrand',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='kgnbrand',
            name='volume_Unit',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_Name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='machine',
            name='postal_Code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='machine',
            name='province',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='machine',
            name='street',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='machine',
            name='waste',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='machineorder',
            name='brand_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='machineorder',
            name='insurance',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='machineorder',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='router',
            name='type',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AddField(
            model_name='machine',
            name='country',
            field=models.CharField(default='Italy', max_length=20),
        ),
    ]
