# Generated by Django 5.0.2 on 2024-04-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgnWebApp', '0003_remove_alarm_address_remove_alarm_on_delay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='threshold',
        ),
        migrations.AddField(
            model_name='alarm',
            name='position',
            field=models.CharField(default='General', max_length=10),
        ),
        migrations.AddField(
            model_name='alarm',
            name='sent',
            field=models.CharField(default='y', max_length=1),
        ),
    ]
