# Generated by Django 5.0.2 on 2024-04-23 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgnWebApp', '0005_remove_alarm_access_category_alter_message_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('role', models.CharField(max_length=200)),
                ('sentmail', models.BooleanField(default=True)),
                ('sentsms', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PLCStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SERRANDA_CHIUSA', models.BooleanField(default=False)),
                ('SERRANDA_APERTA', models.BooleanField(default=False)),
                ('PRESSA_AVANTI', models.BooleanField(default=False)),
                ('PRESSA_INDIETRO', models.BooleanField(default=False)),
                ('CESTA_IN_CARICO', models.BooleanField(default=False)),
                ('CESTA_IN_SCARICO', models.BooleanField(default=False)),
                ('SERRANDA_SICUREZZA_CHIUSA', models.BooleanField(default=False)),
                ('CESTA_SICUREZZA_IN_CARICO', models.BooleanField(default=False)),
                ('CARICO_INGOMBRANTE', models.BooleanField(default=False)),
                ('BORDO_SENSIBILE_INTERVENUTO', models.BooleanField(default=False)),
                ('PORTE_LATERALI_APERTE', models.BooleanField(default=False)),
                ('READY', models.BooleanField(default=False)),
                ('ATTUALE_PRESSIONE', models.BooleanField(default=False)),
                ('ATTUALE_PESO', models.BooleanField(default=False)),
                ('SEQUENZA', models.BooleanField(default=False)),
                ('VERSIONE_PLC', models.BooleanField(default=False)),
                ('PULSANTE_EMERGENZA_INSERITO', models.BooleanField(default=False)),
                ('PULSANTE_RESET_MACCHINA', models.BooleanField(default=False)),
                ('PULSANTE_APRI_SERRANDA', models.BooleanField(default=False)),
                ('PULSANTE_CHIUDI_SERRANDA', models.BooleanField(default=False)),
                ('PULSANTE_AVANTI_PRESSA', models.BooleanField(default=False)),
                ('PULSANTE_INDIETRO_PRESSA', models.BooleanField(default=False)),
                ('PULSANTE_CESTA_IN_CARICO', models.BooleanField(default=False)),
                ('PULSANTE_CESTA_IN_SCARICO', models.BooleanField(default=False)),
                ('PULSANTE_POMPA_IGENIZZANTE', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='plcstatus',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='kgnWebApp.plcstatus'),
        ),
    ]
