# Generated by Django 5.0.2 on 2024-02-19 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KGN_Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_ID', models.CharField(max_length=200)),
                ('Brand_Name', models.CharField(max_length=200)),
                ('SN_Manufacture', models.CharField(max_length=200)),
                ('Online', models.CharField(max_length=200)),
                ('Volume', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PLCConfigIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PLCConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_Name', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=200)),
                ('Waste', models.CharField(max_length=200)),
                ('Start_Avail', models.CharField(max_length=200)),
                ('End_Avail', models.CharField(max_length=200)),
                ('Street', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('Country', models.CharField(max_length=200)),
                ('Sim_card', models.CharField(max_length=200)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kgnWebApp.kgn_brand')),
            ],
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alarm_type', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Severity', models.CharField(max_length=100)),
                ('Condition', models.CharField(max_length=255)),
                ('Threshold', models.BooleanField(default=False)),
                ('Threshold_type', models.CharField(max_length=100)),
                ('On_Delay', models.CharField(max_length=100)),
                ('Operator_Instructions', models.CharField(max_length=255)),
                ('Access_Category', models.CharField(max_length=100)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kgnWebApp.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Machine_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cutomer_ID', models.CharField(max_length=200)),
                ('Cutomer_Name', models.CharField(max_length=200)),
                ('Order_Name', models.CharField(max_length=200)),
                ('Order_ID', models.CharField(max_length=200)),
                ('Order_Date', models.CharField(max_length=200)),
                ('Order_Delivery_Date', models.CharField(max_length=200)),
                ('Pieces', models.CharField(max_length=200)),
                ('Assurance_Plan', models.CharField(max_length=200)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kgnWebApp.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kgnWebApp.question')),
            ],
        ),
    ]
