# Generated by Django 5.0.2 on 2024-02-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kgnWebApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kgn_brand',
            name='Online',
        ),
    ]
