# Generated by Django 5.0.2 on 2024-02-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kgnWebApp', '0002_remove_kgn_brand_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine_order',
            old_name='Cutomer_ID',
            new_name='Customer_ID',
        ),
        migrations.RenameField(
            model_name='machine_order',
            old_name='Cutomer_Name',
            new_name='Customer_Name',
        ),
    ]
