# Generated by Django 5.0.2 on 2024-03-07 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('threshold', models.CharField(max_length=100)),
                ('threshold_Type', models.BooleanField(default=False)),
                ('on_Delay', models.FloatField()),
                ('operator_Instruction', models.CharField(max_length=255)),
                ('access_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KgnBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('volume_Value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_Unit', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PLCData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_1', models.CharField(max_length=600)),
                ('plant_2', models.CharField(max_length=600)),
                ('roll_Up', models.CharField(max_length=600)),
                ('rotation_Drum', models.CharField(max_length=600)),
                ('pmp', models.CharField(max_length=600)),
                ('hydraulic', models.CharField(max_length=600)),
                ('yv_Fwbw', models.CharField(max_length=600)),
                ('field', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PLCIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('unit', models.CharField(max_length=8)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('card_Number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('last_Access', models.DateTimeField(auto_now_add=True)),
                ('phone_Number', models.BigIntegerField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_Name', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('waste', models.CharField(max_length=200)),
                ('start_Available', models.DateField()),
                ('end_Available', models.DateField()),
                ('province', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('postal_Code', models.CharField(max_length=20)),
                ('Country', models.CharField(max_length=200)),
                ('kgnbrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kgnWebApp.kgnbrand')),
                ('plcdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kgnWebApp.plcdata')),
                ('plcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kgnWebApp.plcio')),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_Card', models.DecimalField(decimal_places=0, max_digits=18)),
                ('mac_Address', models.CharField(max_length=100)),
                ('ip_Address', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('version', models.FloatField(blank=True, default=None, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kgnWebApp.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('date_Time', models.DateTimeField(auto_now_add=True)),
                ('category', models.IntegerField()),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kgnWebApp.alarm')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kgnWebApp.machine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kgnWebApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='MachineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order_Date', models.DateField()),
                ('delivery_Date', models.DateField()),
                ('brand_name', models.CharField(max_length=200)),
                ('insurance', models.CharField(max_length=200)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kgnWebApp.machine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kgnWebApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_Change', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kgnWebApp.machine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kgnWebApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kgnWebApp.machine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kgnWebApp.user')),
            ],
        ),
    ]
